name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - agent-fleet-main
      - android-10
  pull_request:
    branches:
      - agent-fleet-main
      - android-10

permissions:
  contents: read

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: gradle/actions/wrapper-validation@0b6dd653ba04f4f93bf581ec31e66cbd7dcb644d # v4
